### ISSUE TITLE
Saving a Button in the StreamPi Server is not possible

### ISSUE THREAD

**Issue by Sinchris2k** [DerEingerostete/StreamPi-Hue#1]
I would like to create a new button for a specific light in the server for my Raspberry Pi 3 (Client).

The Plugin is proberly configured in the server settings. IP is shown, API-Key is there and i gave it an App Name.

I can add a new button "Hue > Toggle Light" and it pops up at the desired location on the client.

But when i am done to set my preferences and click on "Save", the save-Button will get greyed out and i can no longer edit any other button, until i restart the server.

I'm using version 1.0.1 of the plugin.

[stream-pi-server.log](https://github.com/DerEingerostete/StreamPi-Hue/files/11200017/stream-pi-server.log)

**Comment by DerEingerostete** [comment]
Unfortunately, I am unable to reproduce the issue you are experiencing. Could you please provide further details, such as the Stream-Pi version you are currently using, and whether the connect button for Hue under plugins displays "Disconnect" rather than "Connect"? Additionally, could you send a screenshot of your Toggle Light configuration or describe the preferences you have set?

**Comment by Sinchris2k** [comment]
Hi. Sure, i'll try my best to give you the information you asked for :)

The Version i am using as a client is the 1.0.0 EA3 on a Raspberry Pi 3 running Raspbian Bullseye.
The Server is also Version 1.0.0 EA3, running on Windows 11.

The settings for the Hue Plugin displays "Disconnect".
In the log i had attached you can see, that the plugin has connected itself with my HueBridge.

Attached you can find screenshots for the set preferences before and after save as well as an other button further blocked for save as an example until the server is restarted.

![Hue Settings before save](https://user-images.githubusercontent.com/130463886/232290238-0f8a6901-923b-4a87-b95e-6d5a14f039db.jpg)
![Hue Settings after save](https://user-images.githubusercontent.com/130463886/232290244-da9688b1-2399-458b-92a5-feb30a969d59.jpg)
![Example for other button, also blocked after save](https://user-images.githubusercontent.com/130463886/232290250-2df633d3-6bd1-4d2c-a72b-db6c1249c07c.jpg)

**Comment by DerEingerostete** [comment]
Thanks! I have a possible idea why you experience this issue.
The plugin was designed to work with version [2.0.0-SNAPSHOT](https://github.com/stream-pi/serer/releases/tag/2.0.0-SNAPSHOT).

Would you mind making a backup of the Client directory and try upgrading to 2.0.0-SNAPSHOT?
I think this might be the reason you are experiencing this issue.

To upgrade to version 2.0.0-SNAPSHOT, I recommend renaming all the folders created by StreamPi on your Raspberry Pi, and then running the script (https://github.com/stream-pi/scripts/blob/master/client-install-raspberry-pi.sh). You will need to modify the download link to https://github.com/stream-pi/client/releases/download/2.0.0-SNAPSHOT/stream-pi-client-linux-arm32-2.0.0-SNAPSHOT-executable.zip. This should resolve the issue you are facing.

Please let me know if you need any further assistance

**Comment by Sinchris2k** [comment]
Thank you for that info.
I will upgrade to 2.0.0-SNAPSHOT as soon as i am back home on saturday.

Until then thank you very much for your assistance :)

**Comment by Sinchris2k** [comment]
I did the upgrade to 2.0.0-SNAPSHOT and you were right.
The plugin runs just fine under this version.

Thank you again for your help. :)

**Comment by DerEingerostete** [comment]
Okay do that. Please inform me if it worked and / or close the issue yourself if it did

**Comment by Sinchris2k** [comment]
It worked perfectly, thank you.
I hereby close this issue.
